name: everyday-rails-ci
run-name: rspec-ci
on: [ push pull_request ]
jobs:
  exec-rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Switch branch
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.3'
          bundler-cache: true
      - name: bundle install
        run: bin/bundle install
      - name: Migration
        run: bin/rails db:migrate
      - name: Run test
        run: bin/bundle exec rspec
services:
  db:
    image: postgres:15.7
    ports:
      - 5432:5432
    env:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: everyday
      POSTGRES_DB: everyday_test
