name: everyday-rails-ci
run-name: rspec-ci
on: [push]
jobs:
  exec-rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.3'
          bundler-cache: true
      - run: bin/bundle exec rspec
