name: everyday-rails-ci
run-name: rspec-ci
on:
  push:
    branches:
      - 'main'
      - 'feat*'
  pull_request:
    types: [ opened, ready_for_review ]
jobs:
  exec-rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Switch branch
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.3'
          bundler-cache: true
      - name: bundle install
        run: bin/bundle install
      - name: Migration
        env:
          POSTGRES_HOST: localhost
          RAILS_ENV: test
        run: bin/rails db:migrate
      - name: Run test
        env:
          POSTGRES_HOST: localhost
        run: bin/bundle exec rspec
    services:
      db:
        image: postgres:15.7
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: everyday
          POSTGRES_DB: everyday_test
